source 'https://rubygems.org'

gem 'sinatra'
gem 'rerun'
gem 'webrick'
gem 'zaschiff_palindrome'

group :test do
    gem 'minitest'
    gem 'minitest-reporters'
    gem 'rack-test'
    gem 'rake'
    gem 'nokogiri'
end